### ISSUE TITLE
The conflict conditionals result in dead code.

### ISSUE THREAD

**Issue by yanliu18** [galacticcouncil/warehouse#118]
https://github.com/galacticcouncil/warehouse/blob/b7cc6ff5efb641e4fd4da524459ce8111c32aef5/liquidity-mining/src/lib.rs#L1283-L1291

The above two condition checkings are never reachable. The `update_global_farm()` function is always called after the condition ```!global_farm.total_shares_z.is_zero() && global_farm.updated_at != current_period``` is satisfied.

Similar dead code in `update_yield_farm()` where the first two if-condition are not reachable. https://github.com/galacticcouncil/warehouse/blob/174065dab263f45cdedbd528ce85a37b4065ee01/liquidity-mining/src/lib.rs#L1373-L1379.

**Comment by martinfridrich** [comment]
Codebase was refactored and these conditions are reachable now.
