### ISSUE TITLE
Extract asset registry

### ISSUE THREAD

**Issue by jak-pan** [galacticcouncil/warehouse#12]
Extract asset registry and as a part of this change we should remove symbol from the chain as we don't use it anywhere. 
- [ ] remove symbol
- [ ] migrate both basilisk
- [ ] migrate hydradx

**Comment by enthusiastmartin** [comment]
The symbol is actually used. When an asset is being registered - it reuses the same asset id if such symbol already exists.

this is useful, eg for pool share token.

it is possible to remove the symbol and dont reuse asset ids ( or let xyk pallet deal with it ). 

However it also helps identifying which asset if which - no need to keep track outside basilisk what ids belongs to eg, KSM.

**Comment by Roznovjak** [comment]
This [PR](https://github.com/galacticcouncil/warehouse/pull/35) adds the pallet.

**Comment by lumir-mrkva** [comment]
fixed by #35
