### ISSUE TITLE
test: improve test coverage

### ISSUE THREAD

**Issue by enthusiastmartin** [galacticcouncil/warehouse#33]
Improve test coverage of each pallets to be as close to 100% as possible.

currently for some pallets it is very low - eg. multi-payment is around 70%.

**Comment by dmoka** [comment]
Just checked, the multi-payment pallet code coverage has been already improved with some tests by @Roznovjak.

The rest looks fine:
![image](https://user-images.githubusercontent.com/9437108/194889628-c92dba4f-03cb-45b3-9a44-5a22062d554d.png)

**Comment by dmoka** [comment]
Just checked, the multi-payment pallet coverage has been already improved with some tests by @Roznovjak (https://github.com/galacticcouncil/warehouse/pull/80)

The rest of the pallets looks fine in terms of code coverage:
![image](https://user-images.githubusercontent.com/9437108/194898606-b5f9e772-bb73-4d54-870d-857ea6f6b91d.png)

Furthermore, as code coverage can be a misleading metric (as we can easily reach 100% without any test assertion), therefore it would be also handy to strive for high (90-100%) mutation score.

**Comment by dmoka** [comment]
Based on the code coverage and mutation testing analysis, added some missing tests: https://github.com/galacticcouncil/warehouse/pull/85
