### ISSUE TITLE
Multiple issues with the `create_collection()` interface function

### ISSUE THREAD

**Issue by yanliu18** [galacticcouncil/warehouse#97]
There are a few issues with the following code: 
https://github.com/galacticcouncil/warehouse/blob/89bde6d2b8bad2263c554eb3d83b76d877971136/nft/src/lib.rs#L498-L502

- In the `create_collection()` interface quoted in the above code, the collection id `collection` should be checked against the `ReserveCollectionIdUpTo` constant to make sure the collection id does not fall into the reserved id range. 

- The `_admin` argument is passed in but ignored in this function. Since the `do_create_collection()` function in the NFT pallet by default assumes all admins to be the owner, the `_admin` should be removed.

- This function creates a `marketplace` collection type. Is it intentional? It might be merged with the interface function `create_typed_collection()` to simplify the code.
- https://github.com/galacticcouncil/warehouse/blob/89bde6d2b8bad2263c554eb3d83b76d877971136/nft/src/lib.rs#L561

- The metadata is hardcoded as `BoundedVec::default()`. It should be allowed to let the caller pass in meaningful metadata.

**Comment by Roznovjak** [comment]
The `admin` argument is part of the trait we are implementing and we can't change it. For the same reason we use default collection type and metadata, because we can't add them as arguments to `create_collection`. Currently we use both traits (`Create` and `CreateTypedCollection`) so we can't merge them. The implementations are also slightly different. The implementation of `create_collection` is more restrictive and part of `nonfungibles` traits, meant for "public" use.

**Comment by yanliu18** [comment]
> The `admin` argument is part of the trait we are implementing and we can't change it. For the same reason we use default collection type and metadata, because we can't add them as arguments to `create_collection`. Currently we use both traits (`Create` and `CreateTypedCollection`) so we can't merge them. The implementations are also slightly different. The implementation of `create_collection` is more restrictive and part of `nonfungibles` traits, meant for "public" use.

I see. In this case, proper documentation should be added to highlight the differences between the two traits. 

However, I may still think having two traits perform similar operations could be confusing. It seems the `CreateTypedCollection` could also create `marketplace` typed collection. This indicates an overlap between the two traits.

Thus, would it be good to deprecate the trait `Create` while making `CreateTypedCollection` the only way of creating collections? You might also want to allow a `metadata` argument in the `CreateTypedCollection` trait definition to allow customisation.
